### ISSUE TITLE
Support for sparse H?

### ISSUE THREAD

**Issue by e4lam** [asherikov/qpmad#10]
It doesn't seem like your solver supports sparse H? I tried using it but I kept getting compiler errors on MSVC like:
```
...\qpmad-master\include\qpmad\factorization_data.h(56): error C2678: binary '=': no operator found which takes a left-hand operand of type 'const Eigen::TriangularView<const Derived,2>' (or there is no acceptable conversion)
        with
        [
            Derived=Eigen::SparseMatrix<double,0,int>
        ]
```

**Comment by asherikov** [comment]
Hello, no it doesnt, and if I remember correctly it doesnt make much sense to support it -- sparsity pattern is lost very fast during computations. Try converting it to dense, working with sparse matrices is not necessarily faster.
