### ISSUE TITLE
QP Form

### ISSUE THREAD

**Issue by mrsp** [asherikov/qpmad#3]
Hello and thanks for the great repo.

After a bit of search in the repo, I couldn't find the form that qpmad assumes for the underlying QP. 

Is it  min 0.5 * x^T  H  x + g^T  x  or  min x^T  H  x + g^T  x

Maybe put it in the readme :)

Thanks in advance!

**Comment by asherikov** [comment]
Hi, the objective function is `(Ax - b)^T (Ax - b) = x^T A^T A x - 2 b^T A x + b^T b`, the last term is constant and is dropped, the rest is divided by two which gives `0.5 * x^T H x + g^T x`. The solver works with a derivative of the objective function, so 0.5 is eliminated internally. `x^T H x + g^T x` is something weird where either Hessian is divided by two or vector multiplied by two, which is by no means a standard thing.
