### ISSUE TITLE
About lb and ub

### ISSUE THREAD

**Issue by NigerChel** [asherikov/qpmad#6]
Hi qpmad developer, first I want to thank for your great work on this QP solver.

I understand that the arguments taken in this code are as follows:
qpmad::Solver::ReturnStatus status = solver.solve(x, H, h, lb, ub, A, Alb, Aub);

If I don't consider taking into account the lower bound and upper bound, that is, lb an ub. Then
Should the qpmad work as this code?
qpmad::Solver::ReturnStatus status = solver.solve(x, H, h, A, Alb, Aub);

Futhermore, I'm having also this issue "terminate called after throwing an instance of 'std::runtime_error'
  what():  In solve() // Non-negative step lengths expected.". I am using this qpmad for a WBC for a humanoid.

Thanks in advance,
Niger Chel

**Comment by asherikov** [comment]
1. yes, e.g. https://github.com/asherikov/qpmad/blob/master/test/solver_fixtures.h#L114
2. see https://github.com/asherikov/qpmad/issues/2
