### ISSUE TITLE
Compiling with ``EIGEN_MPL2_ONLY``

### ISSUE THREAD

**Issue by stephane-caron** [asherikov/qpmad#9]
First of all, thanks for making an open source QP solver :smiley: 

I tried to compile ``demo.cpp`` with ``EIGEN_MPL2_ONLY``, but it seems this flag excludes the simplicial LLT:

```
include/qpmad/implementation.h:746:26: error: 'SimplicialLLT' in namespace 'Eigen' does not name a template type
  746 |             const Eigen::SimplicialLLT<typename std::decay<decltype(H)>::type, Eigen::Lower> llt(H);
```

Without the flag the example compiles fine.

This might [be an issue](https://github.com/facebookarchive/caffe2/issues/1371) because without ``EIGEN_MPL2_ONLY`` qpmad may pull some LGPL code from Eigen (and thus be LGPL rather than Apache 2.0). I haven't checked if the simplicial LLT specifically is LGPL'd or not.

**Comment by jcarpent** [comment]
Regarding the discussion https://github.com/Simple-Robotics/proxsuite/issues/77#issuecomment-1353252161, it seems that the license of the code within Eigen has changed for the sparse Cholesky backend.

**Comment by stephane-caron** [comment]
Confirmed that we can compile with ``EIGEN_MPL2_ONLY`` as long as Eigen >= 3.4.0. @asherikov perhaps update Eigen's version in the README?

**Comment by asherikov** [comment]
Added a cmake flag -> https://github.com/asherikov/qpmad/commit/53edb8a45f28f25d43b953893bed0fcb15301286
